### PR TITLE
Several fixes to git-rcs-keywords

### PR DESCRIPTION
**Pull request by maghiel**
Hello turon,

I've forked your git-rcs-keywords project, and applied several minor fixes to it. The commits should speak for themselves. I believe the changes are ready to be merged into your project! 
(please do note I am not a perl but php developer).

Thanks again for the great initiative! Your project saves others a lot of time :)

Regards,

Maghiel Dijksman

### CODE REVIEW

**Comment by turon** [comment]
Hi Maghiel,

I'll take a look and merge when I get some time.  Thanks for the initiative! 

Martin

**Comment by maghiel** [comment]
Hello Martin, 
No problem at all, had to make the changes anyway so it was not effort at all to contribute them back.
If there's anything else on this project you need help in don't hesitate to contact me!

Regards,
Maghiel

**Comment by maghiel** [comment]
Hey Martin,

When do you have time to look btw? It's just a few minor changes if you look at the diff. I got some features planned for this project (like an install/configure shell script so the user would require almost no configuration), so I would love to see this pull request already be pulled in ;)

Regards,
Maghiel

**Comment by turon** [comment]
Hi Maghiel,

I merged your changes.  It went pretty smoothly overall, but it doesn't show your fork in the "Network" tab
as I would expect.  I think it might be because I hadn't set:
  git config user.name 'turon'
  git config user.email '...'

Anyway, it seemed to pull in your authorship into the main timeline.  
Thanks for pushing the patches -- they look good.

m++

**Comment by maghiel** [comment]
Hey Martin,

Great! 
It doesnt show my fork in the Network tab, but it does show my commits when you hover over the items in that tab, so I think everything went fine :) If you could credit me somewhere, it be awesome though ;) :p

Do you have any thoughts about where to go with this project btw? 

Regards,
Maghiel

**Pull request merged**
